/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notificaciones` | `/notificaciones`; params?: Router.UnknownInputParams; } | { pathname: `/../context/NotificationContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/ajustes` | `/ajustes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/calendario` | `/calendario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/camera` | `/camera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/reportes` | `/reportes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/notificaciones` | `/notificaciones`; params?: Router.UnknownOutputParams; } | { pathname: `/../context/NotificationContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/ajustes` | `/ajustes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/calendario` | `/calendario`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/camera` | `/camera`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/reportes` | `/reportes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/notificaciones${`?${string}` | `#${string}` | ''}` | `/notificaciones${`?${string}` | `#${string}` | ''}` | `/../context/NotificationContext${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/ajustes${`?${string}` | `#${string}` | ''}` | `/ajustes${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/calendario${`?${string}` | `#${string}` | ''}` | `/calendario${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/camera${`?${string}` | `#${string}` | ''}` | `/camera${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/reportes${`?${string}` | `#${string}` | ''}` | `/reportes${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notificaciones` | `/notificaciones`; params?: Router.UnknownInputParams; } | { pathname: `/../context/NotificationContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/ajustes` | `/ajustes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/calendario` | `/calendario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/camera` | `/camera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/reportes` | `/reportes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; };
    }
  }
}
